//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTACONF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aptadbEntities : DbContext
    {
        public aptadbEntities()
            : base("name=aptadbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authortable> authortable { get; set; }
        public virtual DbSet<conferencetable> conferencetable { get; set; }
        public virtual DbSet<guesttable> guesttable { get; set; }
        public virtual DbSet<papertable> papertable { get; set; }
        public virtual DbSet<reservationtable> reservationtable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
