//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTACONF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conferencetable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public conferencetable()
        {
            this.reservationtable = new HashSet<reservationtable>();
            this.papertable = new HashSet<papertable>();
        }
    
        public int conferenceid { get; set; }
        public string conferencetitle { get; set; }
        public string location { get; set; }
        public string keynotespeaker { get; set; }
        public System.DateTime conferencedate { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservationtable> reservationtable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<papertable> papertable { get; set; }
    }
}
