//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTACONF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guesttable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public guesttable()
        {
            this.reservationtable = new HashSet<reservationtable>();
        }
    
        public int guestid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string contact { get; set; }
        public string address { get; set; }
        public string registrationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservationtable> reservationtable { get; set; }
    }
}
