//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTACONF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class papertable
    {
        public int paperid { get; set; }
        public string papertitle { get; set; }
        public string papertype { get; set; }
        public Nullable<int> authorid { get; set; }
        public Nullable<int> conferenceid { get; set; }
        public string papersize { get; set; }
        public Nullable<System.DateTime> submissiondate { get; set; }
    
        public virtual authortable authortable { get; set; }
        public virtual conferencetable conferencetable { get; set; }
    }
}
