//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTACONF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservationtable
    {
        public int reservationID { get; set; }
        public int conferenceid { get; set; }
        public int guestid { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual guesttable guesttable { get; set; }
        public virtual conferencetable conferencetable { get; set; }
    }
}
